apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odh-deployment-jupyterhub
spec:
  destination:
    namespace: odh-deployment-jupyterhub
    name: dev-cluster
  project: default
  source:
    path: kfdef/jupyterhub
    repoURL: https://github.com/operate-first/odh.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odh-deployment-superset
spec:
  destination:
    namespace: odh-deployment-superset
    name: dev-cluster
  project: default
  source:
    path: kfdef/superset
    repoURL: https://github.com/operate-first/odh.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
